# Site settings
title: zyzzel - a collection of personal experiments
email: ron@zyzzel.com
description: > # this means to ignore newlines until "baseurl:"
  zyzzel is a collection of personal experiments; plain and simple.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zyzzel.com" # the base hostname & protocol for your site
# twitter_username: ronfulkerson
# github_username:  ronfulkerson

# Build settings
markdown: kramdown
